add_test( [==[Array construction]==] /home/runner/work/array/array/_codeql_build_dir/test_runner [==[Array construction]==]  )
set_tests_properties( [==[Array construction]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/array/array/_codeql_build_dir SKIP_RETURN_CODE 4)
add_test( [==[Array element access]==] /home/runner/work/array/array/_codeql_build_dir/test_runner [==[Array element access]==]  )
set_tests_properties( [==[Array element access]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/array/array/_codeql_build_dir SKIP_RETURN_CODE 4)
add_test( [==[Array modification]==] /home/runner/work/array/array/_codeql_build_dir/test_runner [==[Array modification]==]  )
set_tests_properties( [==[Array modification]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/array/array/_codeql_build_dir SKIP_RETURN_CODE 4)
add_test( [==[Array utility functions]==] /home/runner/work/array/array/_codeql_build_dir/test_runner [==[Array utility functions]==]  )
set_tests_properties( [==[Array utility functions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/array/array/_codeql_build_dir SKIP_RETURN_CODE 4)
set( test_runner_TESTS [==[Array construction]==] [==[Array element access]==] [==[Array modification]==] [==[Array utility functions]==])
